### ISSUE TITLE
New-DatabricksCluster not using bearertoken to authenticate

### ISSUE THREAD

**Issue by RichieBzzzt** [DataThirstLtd/azure.databricks.cicd.tools#130]
Scenario - 
I want to get all the clusters from one databricks workspace using ```Get-DatabricksClusters``` and publish them to a different workspace using ```New-DatabricksCluster```. However at no point does ```New-DatabricksWorkspace``` make use of the parameter ```BearerToken``` when calling ```Invoke-DatabricksAPI```.

https://github.com/DataThirstLtd/azure.databricks.cicd.tools/blob/5ebab9a08f31124b99aa283892ed9da46c611b17/Public/New-DatabricksCluster.ps1#L160-L168

This confused me a little bit as bearertoken is mandatory? 

https://github.com/DataThirstLtd/azure.databricks.cicd.tools/blob/5ebab9a08f31124b99aa283892ed9da46c611b17/Public/Invoke-DatabricksAPI.ps1#L34

At any rate, I assume this leads to ```Invoke-DatabricksAPI``` to use some other bearertoken that exists inthe PowerShell session to be used instead?

**Comment by simondmorias** [comment]
This is a "legacy" issue. Previously every command required a BearerToken and Region. But when AAD came along I added Connect-Databricks which would work for the session - rather than add 6 new params to every command.
For backwards compatibility each command added this line:
```
GetHeaders $PSBoundParameters | Out-Null
```

This sets the session Bearer Token (it actually overwrites the Connect-Databricks session if it already exists).

So you should be able to do what you want, but you may not be able to pipe it in a single command. Something like this should work:

```
$Cluster = Get-DatabricksCluster -BearerToken "Workspace1Token" -Region "NorthEurope" -ClusterName "bob"
$Cluster | New-DatabricksCluster -BearerToken "Workspace2Token" -Region "NorthEurope"
```

Either way the session Bearer Token gets set and that is always used.

**Comment by RichieBzzzt** [comment]
OK yes this makes sense and it works, thanks!
